a = input('Digite algo:')
print('É um número:', a.isnumeric())
print('É feito de espaços:', a.isspace())
print('É alfabético:', a.isalpha())
print('É decimal:',a.isdecimal())
print('Qual é o tipo primitivo desse valor:',type(a))
print('É alfanumerico:',a.isalnum())
print('Éstá em maiúscula:',a.isupper())
print('Está em minúscula:',a.islower())
print('Está capitalizada:',a.istitle())