nome = input('Qual é o seu nome?')
idade = input('Qual é a sua idade?')
peso = input('Qual é o seu peso?')
nascimento = input('Qual é sua data de nascimento?')
print('Nome:',nome,',Idade:',idade,',Peso:',peso,',Data de nascimento:',nascimento)